features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
facebook_url: ''
twitter_url: 'https://twitter.com/zymphonies'
google_plus_url: ''
linkedin_url: ''
pinterest_url: 'https://www.pinterest.com/zymphonies'
rss_url: ''
copyright_text: 'Copyright 2015· All rights reserved'
show_social_icon: 1
show_credit_link: 0
show_slideshow: 1
no_of_slides: '3'
slide_title_1: 'Drupal 8 zymphonies theme'
slide_description_1: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since.'
slide_url_1: '#'
slide_image_path_1: /images/slider/slide_01.jpg
slide_title_2: 'Best drupal design & development agency'
slide_description_2: 'long established fact that a reader will be distracted by the readable content of a page when looking at its layout.'
slide_url_2: '#'
slide_image_path_2: /images/slider/slide_02.jpg
slide_title_3: 'Marketing agency'
slide_description_3: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since.'
slide_url_3: '#'
slide_image_path_3: /images/slider/slide_03.jpg
_core:
  default_config_hash: TY6WLYxZaBJKkY4Trvj8R0VVUW8GmqYeBoAayk5l2vw
logo:
  use_default: 0
  path: 'public://2510115-200_0.png'
favicon:
  use_default: 0
  path: ''
slide_image_path1: {  }
slide_image_path2: {  }
slide_image_path3: {  }
