features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  logo: true
  name: true
  node_user_picture: true
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
google_plus_url: 'https://plus.google.com/+ZymphoniesTechnologies'
linkedin_url: 'http://www.linkedin.com/company/zymphonies'
pinterest_url: 'https://www.pinterest.com/zymphonies/'
rss_url: rss.xml
show_social_icon: 1
show_credit_link: 1
show_slideshow: 1
no_of_slides: 1
slide_title_1: 'Drupal 8 Theme'
slide_description_1: 'Lorem Ipsum is simply dummy text of texthe printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since'
slide_url_1: '#'
slide_image_path_1: /images/slider/slide_01.jpg
_core:
  default_config_hash: hTLERC4qR9Xj1liD23Dynov6cO8pzK2sWzHYqw-L3Gs
