schemas:
  bootstrap: 8000
  theone: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://drupal-practice.lndo.site:8080/themes/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://2510115-200_0.png'
  url: ''
  use_default: true
