<?php

/** @file ...*/

use Drupal\node\Entity\Node;

/**
 * Function to create new node
 */

function createNode($count) {
    $node = Node::create(['type' => 'page']);
    $node->set('title', 'TEST PAGE');
    $body = [
    'value' => 'Test page body',
    'format' => 'basic_html',
];

    $node->set('body', $body);
    $node->set('uid', 1);
    $node->setPublished();
    $node->save();
    drupal_set_message('Node created node id: '.$node->id());
}



